// <auto-generated />
using System;
using LOCC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LOCC.Infrastructure.Migrations
{
    [DbContext(typeof(LoccDbContext))]
    partial class LoccDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LOCC.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlertId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IsolationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LikelyExposureZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationAtOnset")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnsetDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecoveryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CaseId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Communication", b =>
                {
                    b.Property<Guid>("CommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Audience")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedEvidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateUsed")
                        .HasColumnType("TEXT");

                    b.HasKey("CommunicationId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.ToTable("Communications");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.EvidenceSource", b =>
                {
                    b.Property<Guid>("EvidenceSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliesToModule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jurisdiction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EvidenceSourceId");

                    b.ToTable("EvidenceSources");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultOutbreakPlanLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FacilityType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyContacts")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicHealthUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("INTEGER");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.FacilityRoom", b =>
                {
                    b.Property<int>("FacilityRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CohortAssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CohortRationale")
                        .HasColumnType("TEXT");

                    b.Property<string>("CohortStatus")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnhancedPrecautionsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConfirmedCase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSuspectedCase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIsolationRoom")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastExposureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskZoneStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TerminalCleanRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoningNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("FacilityRoomId");

                    b.ToTable("FacilityRooms");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Intervention", b =>
                {
                    b.Property<Guid>("InterventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntendedOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("TEXT");

                    b.HasKey("InterventionId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CleaningStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CohortingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Wing")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.OutbreakEvent", b =>
                {
                    b.Property<Guid>("OutbreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AIIMSStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeclared")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFirstDetected")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IncidentControllerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutbreakPhase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutbreakType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pathogen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StandDownDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OutbreakId");

                    b.HasIndex("FacilityId");

                    b.ToTable("OutbreakEvents");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RiskAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecommendationId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.RecoveryBAU", b =>
                {
                    b.Property<Guid>("RecoveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ActiveCasesScore")
                        .HasColumnType("REAL");

                    b.Property<double>("BAUReadinessScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("CanStandDown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DebriefCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnvironmentScore")
                        .HasColumnType("REAL");

                    b.Property<double>("IPCComplianceScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QIActionsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedNextStep")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryPhase")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ResidentWellbeingScore")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkforceScore")
                        .HasColumnType("REAL");

                    b.HasKey("RecoveryId");

                    b.HasIndex("OutbreakId")
                        .IsUnique();

                    b.ToTable("RecoveryBAUs");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineWellbeing")
                        .HasColumnType("TEXT");

                    b.Property<string>("CognitionRisk")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolationDistressRisk")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilityStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("RespiratoryRisk")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VaccinationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Wing")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidentId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyBurnRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyUsageRate")
                        .HasColumnType("REAL");

                    b.Property<int>("DaysRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumSafeStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectedDaysRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<Guid>("RiskAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPCInterpretation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RiskAssessmentId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.ToTable("RiskAssessments");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.SituationAwarenessItem", b =>
                {
                    b.Property<int>("SituationAwarenessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interpretation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutbreakId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SituationAwarenessItemId");

                    b.ToTable("SituationAwarenessItems");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWorkInOutbreakZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentWorkZone")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatigueRisk")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InfectionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastShiftDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsualWorkArea")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.SurveillanceCase", b =>
                {
                    b.Property<Guid>("SurveillanceCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntiviralStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deceased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HospitalTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IsolationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IsolationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jurisdiction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pathogen")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicHealthNotificationStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveryDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SymptomOnsetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptoms")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestType")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaccinationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zone")
                        .HasColumnType("TEXT");

                    b.HasKey("SurveillanceCaseId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.ToTable("SurveillanceCases");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.SymptomRecord", b =>
                {
                    b.Property<Guid>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BehaviourChange")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClinicalConcernLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cough")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fever")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GastroSymptoms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShortnessOfBreath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoreThroat")
                        .HasColumnType("INTEGER");

                    b.HasKey("SymptomId");

                    b.HasIndex("CaseId");

                    b.ToTable("SymptomRecords");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.TaskAction", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AIIMSFunction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionRationale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenceRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedFrom")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutbreakEventOutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutbreakId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RiskAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("OutbreakEventOutbreakId");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("TaskActions");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.TestRecord", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnteredBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathogenTested")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.HasIndex("CaseId");

                    b.ToTable("TestRecords");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Case", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany("Cases")
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Communication", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany("Communications")
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany()
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.HasOne("LOCC.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutbreakEvent");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Location", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Facility", "Facility")
                        .WithMany("Locations")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.OutbreakEvent", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Facility", "Facility")
                        .WithMany("OutbreakEvents")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany()
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.HasOne("LOCC.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany()
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OutbreakEvent");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.RecoveryBAU", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithOne("RecoveryBAU")
                        .HasForeignKey("LOCC.Domain.Entities.RecoveryBAU", "OutbreakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Resident", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Facility", "Facility")
                        .WithMany("Residents")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Resource", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany("Resources")
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany()
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Staff", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Facility", "Facility")
                        .WithMany("Staff")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.SurveillanceCase", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany()
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.Navigation("OutbreakEvent");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.SymptomRecord", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Case", "Case")
                        .WithMany("SymptomRecords")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.TaskAction", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.OutbreakEvent", "OutbreakEvent")
                        .WithMany("Tasks")
                        .HasForeignKey("OutbreakEventOutbreakId");

                    b.HasOne("LOCC.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LOCC.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany()
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OutbreakEvent");

                    b.Navigation("Recommendation");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.TestRecord", b =>
                {
                    b.HasOne("LOCC.Domain.Entities.Case", "Case")
                        .WithMany("TestRecords")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Case", b =>
                {
                    b.Navigation("SymptomRecords");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("OutbreakEvents");

                    b.Navigation("Residents");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LOCC.Domain.Entities.OutbreakEvent", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Communications");

                    b.Navigation("RecoveryBAU");

                    b.Navigation("Resources");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
